/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.samplesystem.sample.api;

import com.example.samplesystem.sample.model.CountResponse;
import com.example.samplesystem.sample.model.HelloWorldResponse;
import com.example.samplesystem.sample.model.Ytorderadd;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for Zgl000ControllerApi
 */
@Ignore
public class Zgl000ControllerApiTest {

    private final Zgl000ControllerApi api = new Zgl000ControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAsyncTest() {
        String name = null;
        HelloWorldResponse response = api.getAsync(name);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getHelloTest() {
        String name = null;
        HelloWorldResponse response = api.getHello(name);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrdersTest() {
        List<Ytorderadd> response = api.getOrders();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRfcTest() {
        String name = null;
        HelloWorldResponse response = api.getRfc(name);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void putOrdersTest() {
        Ytorderadd ytorderadd = null;
        CountResponse response = api.putOrders(ytorderadd);

        // TODO: test validations
    }
    
}
