
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.60.0
 */

package com.mycompany.vdm.namespaces.es5;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.mycompany.vdm.services.Es5Service;
import com.sap.cloud.sdk.datamodel.odata.client.request.ODataEntityKey;
import com.sap.cloud.sdk.datamodel.odatav4.core.SimpleProperty;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntity;
import com.sap.cloud.sdk.datamodel.odatav4.core.VdmEntitySet;
import com.sap.cloud.sdk.result.ElementName;
import io.vavr.control.Option;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;


/**
 * <p>Original entity name from the Odata EDM: <b>V_orderitems</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.datamodel.odatav4.adapter.GsonVdmAdapterFactory.class)
@JsonSerialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectSerializer.class)
@JsonDeserialize(using = com.sap.cloud.sdk.datamodel.odatav4.adapter.JacksonVdmObjectDeserializer.class)
public class V_orderitems
    extends VdmEntity<V_orderitems>
    implements VdmEntitySet
{

    @Getter
    private final java.lang.String odataType = "OrdersServiceNoAuth.V_orderitems";
    /**
     * Selector for all available fields of V_orderitems.
     * 
     */
    public final static SimpleProperty<V_orderitems> ALL_FIELDS = all();
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>MANDT</b></p>
     * 
     * @return
     *     SAPClientID
     */
    @Nullable
    @ElementName("MANDT")
    private java.lang.String sAPClientID;
    public final static SimpleProperty.String<V_orderitems> SAP_CLIENT_ID = new SimpleProperty.String<V_orderitems>(V_orderitems.class, "MANDT");
    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>ORDERID</b></p>
     * 
     * @return
     *     OrderID
     */
    @Nullable
    @ElementName("ORDERID")
    private java.lang.String orderID;
    public final static SimpleProperty.String<V_orderitems> ORDER_ID = new SimpleProperty.String<V_orderitems>(V_orderitems.class, "ORDERID");
    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ORDERITEMID</b></p>
     * 
     * @return
     *     OrderItemID
     */
    @Nullable
    @ElementName("ORDERITEMID")
    private Integer orderItemID;
    public final static SimpleProperty.NumericInteger<V_orderitems> ORDER_ITEM_ID = new SimpleProperty.NumericInteger<V_orderitems>(V_orderitems.class, "ORDERITEMID");
    /**
     * Constraints: Nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>PRODUCTID</b></p>
     * 
     * @return
     *     ProductID
     */
    @Nullable
    @ElementName("PRODUCTID")
    private java.lang.String productID;
    public final static SimpleProperty.String<V_orderitems> PRODUCT_ID = new SimpleProperty.String<V_orderitems>(V_orderitems.class, "PRODUCTID");
    /**
     * Constraints: Nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>PRODUCTNAME</b></p>
     * 
     * @return
     *     ProductName
     */
    @Nullable
    @ElementName("PRODUCTNAME")
    private java.lang.String productName;
    public final static SimpleProperty.String<V_orderitems> PRODUCT_NAME = new SimpleProperty.String<V_orderitems>(V_orderitems.class, "PRODUCTNAME");
    /**
     * Navigation property <b>ORDERS</b> for <b>V_orderitems</b> to single <b>V_orders</b>.
     * 
     */
    @ElementName("ORDERS")
    @Nullable
    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private V_orders toORDERS;
    /**
     * Use with available request builders to apply the <b>ORDERS</b> navigation property to query operations.
     * 
     */
    public final static com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<V_orderitems, V_orders> TO_ORDERS = new com.sap.cloud.sdk.datamodel.odatav4.core.NavigationProperty.Single<V_orderitems, V_orders>(V_orderitems.class, "ORDERS", V_orders.class);

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<V_orderitems> getType() {
        return V_orderitems.class;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 3 <p>Original property name from the Odata EDM: <b>MANDT</b></p>
     * 
     * @param sAPClientID
     *     SAPClientID
     */
    public void setSAPClientID(
        @Nullable
        final java.lang.String sAPClientID) {
        rememberChangedField("MANDT", this.sAPClientID);
        this.sAPClientID = sAPClientID;
    }

    /**
     * (Key Field) Constraints: Not nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>ORDERID</b></p>
     * 
     * @param orderID
     *     OrderID
     */
    public void setOrderID(
        @Nullable
        final java.lang.String orderID) {
        rememberChangedField("ORDERID", this.orderID);
        this.orderID = orderID;
    }

    /**
     * (Key Field) Constraints: Not nullable<p>Original property name from the Odata EDM: <b>ORDERITEMID</b></p>
     * 
     * @param orderItemID
     *     OrderItemID
     */
    public void setOrderItemID(
        @Nullable
        final Integer orderItemID) {
        rememberChangedField("ORDERITEMID", this.orderItemID);
        this.orderItemID = orderItemID;
    }

    /**
     * Constraints: Nullable, Maximum length: 10 <p>Original property name from the Odata EDM: <b>PRODUCTID</b></p>
     * 
     * @param productID
     *     ProductID
     */
    public void setProductID(
        @Nullable
        final java.lang.String productID) {
        rememberChangedField("PRODUCTID", this.productID);
        this.productID = productID;
    }

    /**
     * Constraints: Nullable, Maximum length: 50 <p>Original property name from the Odata EDM: <b>PRODUCTNAME</b></p>
     * 
     * @param productName
     *     ProductName
     */
    public void setProductName(
        @Nullable
        final java.lang.String productName) {
        rememberChangedField("PRODUCTNAME", this.productName);
        this.productName = productName;
    }

    @Override
    protected java.lang.String getEntityCollection() {
        return "V_orderitems";
    }

    @Nonnull
    @Override
    protected ODataEntityKey getKey() {
        final ODataEntityKey entityKey = super.getKey();
        entityKey.addKeyProperty("MANDT", getSAPClientID());
        entityKey.addKeyProperty("ORDERID", getOrderID());
        entityKey.addKeyProperty("ORDERITEMID", getOrderItemID());
        return entityKey;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfFields() {
        final Map<java.lang.String, Object> values = super.toMapOfFields();
        values.put("MANDT", getSAPClientID());
        values.put("ORDERID", getOrderID());
        values.put("ORDERITEMID", getOrderItemID());
        values.put("PRODUCTID", getProductID());
        values.put("PRODUCTNAME", getProductName());
        return values;
    }

    @Override
    protected void fromMap(final Map<java.lang.String, Object> inputValues) {
        final Map<java.lang.String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("MANDT")) {
                final Object value = values.remove("MANDT");
                if ((value == null)||(!value.equals(getSAPClientID()))) {
                    setSAPClientID(((java.lang.String) value));
                }
            }
            if (values.containsKey("ORDERID")) {
                final Object value = values.remove("ORDERID");
                if ((value == null)||(!value.equals(getOrderID()))) {
                    setOrderID(((java.lang.String) value));
                }
            }
            if (values.containsKey("ORDERITEMID")) {
                final Object value = values.remove("ORDERITEMID");
                if ((value == null)||(!value.equals(getOrderItemID()))) {
                    setOrderItemID(((Integer) value));
                }
            }
            if (values.containsKey("PRODUCTID")) {
                final Object value = values.remove("PRODUCTID");
                if ((value == null)||(!value.equals(getProductID()))) {
                    setProductID(((java.lang.String) value));
                }
            }
            if (values.containsKey("PRODUCTNAME")) {
                final Object value = values.remove("PRODUCTNAME");
                if ((value == null)||(!value.equals(getProductName()))) {
                    setProductName(((java.lang.String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
            if ((values).containsKey("ORDERS")) {
                final Object value = (values).remove("ORDERS");
                if (value instanceof Map) {
                    if (toORDERS == null) {
                        toORDERS = new V_orders();
                    }
                    @SuppressWarnings("unchecked")
                    final Map<java.lang.String, Object> inputMap = ((Map<java.lang.String, Object> ) value);
                    toORDERS.fromMap(inputMap);
                }
            }
        }
        super.fromMap(values);
    }

    @Override
    protected java.lang.String getDefaultServicePath() {
        return Es5Service.DEFAULT_SERVICE_PATH;
    }

    @Nonnull
    @Override
    protected Map<java.lang.String, Object> toMapOfNavigationProperties() {
        final Map<java.lang.String, Object> values = super.toMapOfNavigationProperties();
        if (toORDERS!= null) {
            (values).put("ORDERS", toORDERS);
        }
        return values;
    }

    /**
     * Retrieval of associated <b>V_orders</b> entity (one to one). This corresponds to the OData navigation property <b>ORDERS</b>.
     * <p>
     * If the navigation property for an entity <b>V_orderitems</b> has not been resolved yet, this method will <b>not query</b> further information. Instead its <code>Option</code> result state will be <code>empty</code>.
     * 
     * @return
     *     If the information for navigation property <b>ORDERS</b> is already loaded, the result will contain the <b>V_orders</b> entity. If not, an <code>Option</code> with result state <code>empty</code> is returned.
     */
    @Nonnull
    public Option<V_orders> getORDERSIfPresent() {
        return Option.of(toORDERS);
    }

    /**
     * Overwrites the associated <b>V_orders</b> entity for the loaded navigation property <b>ORDERS</b>.
     * 
     * @param value
     *     New <b>V_orders</b> entity.
     */
    public void setORDERS(final V_orders value) {
        toORDERS = value;
    }


    /**
     * Helper class to allow for fluent creation of V_orderitems instances.
     * 
     */
    public final static class V_orderitemsBuilder {

        private V_orders toORDERS;

        private V_orderitems.V_orderitemsBuilder toORDERS(final V_orders value) {
            toORDERS = value;
            return this;
        }

        /**
         * Navigation property <b>ORDERS</b> for <b>V_orderitems</b> to single <b>V_orders</b>.
         * 
         * @param value
         *     The V_orders to build this V_orderitems with.
         * @return
         *     This Builder to allow for a fluent interface.
         */
        @Nonnull
        public V_orderitems.V_orderitemsBuilder orderS(final V_orders value) {
            return toORDERS(value);
        }

    }

}
