/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.samplesystem.sample.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Ytorderadd
 */
public class YtorderaddTest {
    private final Ytorderadd model = new Ytorderadd();

    /**
     * Model tests for Ytorderadd
     */
    @Test
    public void testYtorderadd() {
        // TODO: test Ytorderadd
    }

    /**
     * Test the property 'mandt'
     */
    @Test
    public void mandtTest() {
        // TODO: test mandt
    }

    /**
     * Test the property 'ybukrs'
     */
    @Test
    public void ybukrsTest() {
        // TODO: test ybukrs
    }

    /**
     * Test the property 'ybeln'
     */
    @Test
    public void ybelnTest() {
        // TODO: test ybeln
    }

    /**
     * Test the property 'yreasoncd'
     */
    @Test
    public void yreasoncdTest() {
        // TODO: test yreasoncd
    }

    /**
     * Test the property 'yreasons'
     */
    @Test
    public void yreasonsTest() {
        // TODO: test yreasons
    }

}
