
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.60.0
 */

package com.mycompany.vdm.services;

import javax.annotation.Nonnull;
import com.mycompany.vdm.namespaces.es5.V_orderitems;
import com.mycompany.vdm.namespaces.es5.V_orders;
import com.sap.cloud.sdk.datamodel.odatav4.core.BatchRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.CreateRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder;
import com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>es5</td></tr></table>
 * 
 */
public interface Es5Service {

    /**
     * If no other path was provided via the {@link #withServicePath(String)} method, this is the default service path used to access the endpoint.
     * 
     */
    String DEFAULT_SERVICE_PATH = "odata/v4/OrdersServiceNoAuth";

    /**
     * Overrides the default service path and returns a new service instance with the specified service path. Also adjusts the respective entity URLs.
     * 
     * @param servicePath
     *     Service path that will override the default.
     * @return
     *     A new service instance with the specified service path.
     */
    @Nonnull
    Es5Service withServicePath(
        @Nonnull
        final String servicePath);

    /**
     * Creates a batch request builder object.
     * 
     * @return
     *     A request builder to handle batch operation on this service. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.BatchRequestBuilder#execute(HttpDestinationProperties) execute} method on the request builder object.
     */
    @Nonnull
    BatchRequestBuilder batch();

    /**
     * Fetch multiple {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entities.
     * 
     * @return
     *     A request builder to fetch multiple {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orders>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetAllRequestBuilder<V_orders> getAllV_orders();

    /**
     * Fetch the number of entries from the {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orders>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CountRequestBuilder<V_orders> countV_orders();

    /**
     * Fetch a single {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity using key fields.
     * 
     * @param orderID
     *     OrderID<p>Constraints: Not nullable, Maximum length: 10</p>
     * @param sAPClientID
     *     SAPClientID<p>Constraints: Not nullable, Maximum length: 3</p>
     * @return
     *     A request builder to fetch a single {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orders>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<V_orders> getV_ordersByKey(
        @Nonnull
        final String sAPClientID,
        @Nonnull
        final String orderID);

    /**
     * Create a new {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity and save it to the S/4HANA system.
     * 
     * @param v_orders
     *     {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity object that will be created in the S/4HANA system.
     * @return
     *     A request builder to create a new {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CreateRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orders>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CreateRequestBuilder<V_orders> createV_orders(
        @Nonnull
        final V_orders v_orders);

    /**
     * Update an existing {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity and save it to the S/4HANA system.
     * 
     * @param v_orders
     *     {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity object that will be updated in the S/4HANA system.
     * @return
     *     A request builder to update an existing {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orders>#execute execute} method on the request builder object. 
     */
    @Nonnull
    UpdateRequestBuilder<V_orders> updateV_orders(
        @Nonnull
        final V_orders v_orders);

    /**
     * Deletes an existing {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity in the S/4HANA system.
     * 
     * @param v_orders
     *     {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A request builder to delete an existing {@link com.mycompany.vdm.namespaces.es5.V_orders V_orders} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orders>#execute execute} method on the request builder object. 
     */
    @Nonnull
    DeleteRequestBuilder<V_orders> deleteV_orders(
        @Nonnull
        final V_orders v_orders);

    /**
     * Fetch multiple {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entities.
     * 
     * @return
     *     A request builder to fetch multiple {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetAllRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orderitems>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetAllRequestBuilder<V_orderitems> getAllV_orderitems();

    /**
     * Fetch the number of entries from the {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity collection matching the filter and search expressions.
     * 
     * @return
     *     A request builder to fetch the count of {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entities. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CountRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orderitems>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CountRequestBuilder<V_orderitems> countV_orderitems();

    /**
     * Fetch a single {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity using key fields.
     * 
     * @param orderID
     *     OrderID<p>Constraints: Not nullable, Maximum length: 10</p>
     * @param orderItemID
     *     OrderItemID<p>Constraints: Not nullable</p>
     * @param sAPClientID
     *     SAPClientID<p>Constraints: Not nullable, Maximum length: 3</p>
     * @return
     *     A request builder to fetch a single {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity using key fields. This request builder allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.GetByKeyRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orderitems>#execute execute} method on the request builder object. 
     */
    @Nonnull
    GetByKeyRequestBuilder<V_orderitems> getV_orderitemsByKey(
        @Nonnull
        final String sAPClientID,
        @Nonnull
        final String orderID,
        @Nonnull
        final Integer orderItemID);

    /**
     * Create a new {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity and save it to the S/4HANA system.
     * 
     * @param v_orderitems
     *     {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity object that will be created in the S/4HANA system.
     * @return
     *     A request builder to create a new {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.CreateRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orderitems>#execute execute} method on the request builder object. 
     */
    @Nonnull
    CreateRequestBuilder<V_orderitems> createV_orderitems(
        @Nonnull
        final V_orderitems v_orderitems);

    /**
     * Update an existing {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity and save it to the S/4HANA system.
     * 
     * @param v_orderitems
     *     {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity object that will be updated in the S/4HANA system.
     * @return
     *     A request builder to update an existing {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.UpdateRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orderitems>#execute execute} method on the request builder object. 
     */
    @Nonnull
    UpdateRequestBuilder<V_orderitems> updateV_orderitems(
        @Nonnull
        final V_orderitems v_orderitems);

    /**
     * Deletes an existing {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity in the S/4HANA system.
     * 
     * @param v_orderitems
     *     {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A request builder to delete an existing {@link com.mycompany.vdm.namespaces.es5.V_orderitems V_orderitems} entity. To perform execution, call the {@link com.sap.cloud.sdk.datamodel.odatav4.core.DeleteRequestBuilder<com.mycompany.vdm.namespaces.es5.V_orderitems>#execute execute} method on the request builder object. 
     */
    @Nonnull
    DeleteRequestBuilder<V_orderitems> deleteV_orderitems(
        @Nonnull
        final V_orderitems v_orderitems);

}
